spring.application.name=virtual-thread-performance-analyzer
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.enabled=true
benchmark.platform-thread-pool-size=200
benchmark.simulated-io-delay-ms=100